360p.m3u8:
 - live1
 - live2
 - live3
 - live5
 - live6
 - live8
 - live341
 - live342
 - live343
 - live31
 - live32
 - live33
 - live35
 - live36
 - live37
 - live101
 - live102
 - live103
 - live105
 - live106
 - live108
 - live109
 - dt1
 - dt31
 - sd1
 - sd2
 - rou1
 - sb1
 - nn31
 - sg1
 - ft1
 - fish1
 - 28bar1